<?php
return [
    ["id" => 1, "name" => "آذرشهر", "province_id" => 1],
    ["id" => 2, "name" => "اسکو", "province_id" => 1],
    ["id" => 3, "name" => "اهر", "province_id" => 1],
    ["id" => 4, "name" => "بستان آباد", "province_id" => 1],
    ["id" => 5, "name" => "بناب", "province_id" => 1],
    ["id" => 6, "name" => "تبریز", "province_id" => 1],
    ["id" => 7, "name" => "جلفا", "province_id" => 1],
    ["id" => 8, "name" => "چاراویماق", "province_id" => 1],
    ["id" => 9, "name" => "خداآفرین", "province_id" => 1],
    ["id" => 10, "name" => "سراب", "province_id" => 1],
    ["id" => 11, "name" => "شبستر", "province_id" => 1],
    ["id" => 12, "name" => "عجب شیر", "province_id" => 1],
    ["id" => 13, "name" => "کلیبر", "province_id" => 1],
    ["id" => 14, "name" => "مراغه", "province_id" => 1],
    ["id" => 15, "name" => "مرند", "province_id" => 1],
    ["id" => 16, "name" => "ملکان", "province_id" => 1],
    ["id" => 17, "name" => "میانه", "province_id" => 1],
    ["id" => 18, "name" => "ورزقان", "province_id" => 1],
    ["id" => 19, "name" => "هریس", "province_id" => 1],
    ["id" => 20, "name" => "هشترود", "province_id" => 1],
    ["id" => 21, "name" => "ارومیه", "province_id" => 2],
    ["id" => 22, "name" => "اشنویه", "province_id" => 2],
    ["id" => 23, "name" => "بوکان", "province_id" => 2],
    ["id" => 24, "name" => "پلدشت", "province_id" => 2],
    ["id" => 25, "name" => "پیرانشهر", "province_id" => 2],
    ["id" => 26, "name" => "تکاب", "province_id" => 2],
    ["id" => 27, "name" => "چالدران", "province_id" => 2],
    ["id" => 28, "name" => "چایپاره", "province_id" => 2],
    ["id" => 29, "name" => "خوی", "province_id" => 2],
    ["id" => 30, "name" => "سردشت", "province_id" => 2],
    ["id" => 31, "name" => "سلماس", "province_id" => 2],
    ["id" => 32, "name" => "شاهین دژ", "province_id" => 2],
    ["id" => 33, "name" => "شوط", "province_id" => 2],
    ["id" => 34, "name" => "ماکو", "province_id" => 2],
    ["id" => 35, "name" => "مهاباد", "province_id" => 2],
    ["id" => 36, "name" => "میاندوآب", "province_id" => 2],
    ["id" => 37, "name" => "نقده", "province_id" => 2],
    ["id" => 38, "name" => "اردبیل", "province_id" => 3],
    ["id" => 39, "name" => "بیله سوار", "province_id" => 3],
    ["id" => 40, "name" => "پارس آباد", "province_id" => 3],
    ["id" => 41, "name" => "خلخال", "province_id" => 3],
    ["id" => 42, "name" => "سرعین", "province_id" => 3],
    ["id" => 43, "name" => "کوثر", "province_id" => 3],
    ["id" => 44, "name" => "گرمی", "province_id" => 3],
    ["id" => 45, "name" => "مشگین شهر", "province_id" => 3],
    ["id" => 46, "name" => "نمین", "province_id" => 3],
    ["id" => 47, "name" => "نیر", "province_id" => 3],
    ["id" => 48, "name" => "آران وبیدگل", "province_id" => 4],
    ["id" => 49, "name" => "اردستان", "province_id" => 4],
    ["id" => 50, "name" => "اصفهان", "province_id" => 4],
    ["id" => 51, "name" => "برخوار", "province_id" => 4],
    ["id" => 52, "name" => "بو یین و میاندشت", "province_id" => 4],
    ["id" => 53, "name" => "تیران وکرون", "province_id" => 4],
    ["id" => 54, "name" => "چادگان", "province_id" => 4],
    ["id" => 55, "name" => "خمینی شهر", "province_id" => 4],
    ["id" => 56, "name" => "خوانسار", "province_id" => 4],
    ["id" => 57, "name" => "خور و بیابانک", "province_id" => 4],
    ["id" => 58, "name" => "دهاقان", "province_id" => 4],
    ["id" => 59, "name" => "سمیرم", "province_id" => 4],
    ["id" => 60, "name" => "شاهین شهرومیمه", "province_id" => 4],
    ["id" => 61, "name" => "شهرضا", "province_id" => 4],
    ["id" => 62, "name" => "فریدن", "province_id" => 4],
    ["id" => 63, "name" => "فریدونشهر", "province_id" => 4],
    ["id" => 64, "name" => "فلاورجان", "province_id" => 4],
    ["id" => 65, "name" => "کاشان", "province_id" => 4],
    ["id" => 66, "name" => "گلپایگان", "province_id" => 4],
    ["id" => 67, "name" => "لنجان", "province_id" => 4],
    ["id" => 68, "name" => "مبارکه", "province_id" => 4],
    ["id" => 69, "name" => "نایین", "province_id" => 4],
    ["id" => 70, "name" => "نجف آباد", "province_id" => 4],
    ["id" => 71, "name" => "نطنز", "province_id" => 4],
    ["id" => 72, "name" => "اشتهارد", "province_id" => 5],
    ["id" => 73, "name" => "ساوجبلاغ", "province_id" => 5],
    ["id" => 74, "name" => "طالقان", "province_id" => 5],
    ["id" => 75, "name" => "فردیس", "province_id" => 5],
    ["id" => 76, "name" => "کرج", "province_id" => 5],
    ["id" => 77, "name" => "نظرآباد", "province_id" => 5],
    ["id" => 78, "name" => "آبدانان", "province_id" => 6],
    ["id" => 79, "name" => "ایلام", "province_id" => 6],
    ["id" => 80, "name" => "ایوان", "province_id" => 6],
    ["id" => 81, "name" => "بدره", "province_id" => 6],
    ["id" => 82, "name" => "چرداول", "province_id" => 6],
    ["id" => 83, "name" => "دره شهر", "province_id" => 6],
    ["id" => 84, "name" => "دهلران", "province_id" => 6],
    ["id" => 85, "name" => "سیروان", "province_id" => 6],
    ["id" => 86, "name" => "ملکشاهی", "province_id" => 6],
    ["id" => 87, "name" => "مهران", "province_id" => 6],
    ["id" => 88, "name" => "بوشهر", "province_id" => 7],
    ["id" => 89, "name" => "تنگستان", "province_id" => 7],
    ["id" => 90, "name" => "جم", "province_id" => 7],
    ["id" => 91, "name" => "دشتستان", "province_id" => 7],
    ["id" => 92, "name" => "دشتی", "province_id" => 7],
    ["id" => 93, "name" => "دیر", "province_id" => 7],
    ["id" => 94, "name" => "دیلم", "province_id" => 7],
    ["id" => 95, "name" => "عسلویه", "province_id" => 7],
    ["id" => 96, "name" => "کنگان", "province_id" => 7],
    ["id" => 97, "name" => "گناوه", "province_id" => 7],
    ["id" => 98, "name" => "اسلامشهر", "province_id" => 8],
    ["id" => 99, "name" => "بهارستان", "province_id" => 8],
    ["id" => 100, "name" => "پاکدشت", "province_id" => 8],
    ["id" => 101, "name" => "پردیس", "province_id" => 8],
    ["id" => 102, "name" => "پیشوا", "province_id" => 8],
    ["id" => 103, "name" => "تهران", "province_id" => 8],
    ["id" => 104, "name" => "دماوند", "province_id" => 8],
    ["id" => 105, "name" => "رباطکریم", "province_id" => 8],
    ["id" => 106, "name" => "ری", "province_id" => 8],
    ["id" => 107, "name" => "شمیرانات", "province_id" => 8],
    ["id" => 108, "name" => "شهریار", "province_id" => 8],
    ["id" => 109, "name" => "فیروزکوه", "province_id" => 8],
    ["id" => 110, "name" => "قدس", "province_id" => 8],
    ["id" => 111, "name" => "قرچک", "province_id" => 8],
    ["id" => 112, "name" => "ملارد", "province_id" => 8],
    ["id" => 113, "name" => "ورامین", "province_id" => 8],
    ["id" => 114, "name" => "اردل", "province_id" => 9],
    ["id" => 115, "name" => "بروجن", "province_id" => 9],
    ["id" => 116, "name" => "بن", "province_id" => 9],
    ["id" => 117, "name" => "سامان", "province_id" => 9],
    ["id" => 118, "name" => "شهرکرد", "province_id" => 9],
    ["id" => 119, "name" => "فارسان", "province_id" => 9],
    ["id" => 120, "name" => "کوهرنگ", "province_id" => 9],
    ["id" => 121, "name" => "کیار", "province_id" => 9],
    ["id" => 122, "name" => "لردگان", "province_id" => 9],
    ["id" => 123, "name" => "بشرویه", "province_id" => 10],
    ["id" => 124, "name" => "بیرجند", "province_id" => 10],
    ["id" => 125, "name" => "خوسف", "province_id" => 10],
    ["id" => 126, "name" => "درمیان", "province_id" => 10],
    ["id" => 127, "name" => "زیرکوه", "province_id" => 10],
    ["id" => 128, "name" => "سرایان", "province_id" => 10],
    ["id" => 129, "name" => "سربیشه", "province_id" => 10],
    ["id" => 130, "name" => "طبس", "province_id" => 10],
    ["id" => 131, "name" => "فردوس", "province_id" => 10],
    ["id" => 132, "name" => "قاینات", "province_id" => 10],
    ["id" => 133, "name" => "نهبندان", "province_id" => 10],
    ["id" => 134, "name" => "باخرز", "province_id" => 11],
    ["id" => 135, "name" => "بجستان", "province_id" => 11],
    ["id" => 136, "name" => "بردسکن", "province_id" => 11],
    ["id" => 137, "name" => "بینالود", "province_id" => 11],
    ["id" => 138, "name" => "تایباد", "province_id" => 11],
    ["id" => 139, "name" => "تربت جام", "province_id" => 11],
    ["id" => 140, "name" => "تربت حیدریه", "province_id" => 11],
    ["id" => 141, "name" => "جغتای", "province_id" => 11],
    ["id" => 142, "name" => "جوین", "province_id" => 11],
    ["id" => 143, "name" => "چناران", "province_id" => 11],
    ["id" => 144, "name" => "خلیل آباد", "province_id" => 11],
    ["id" => 145, "name" => "خواف", "province_id" => 11],
    ["id" => 146, "name" => "خوشاب", "province_id" => 11],
    ["id" => 147, "name" => "داورزن", "province_id" => 11],
    ["id" => 148, "name" => "درگز", "province_id" => 11],
    ["id" => 149, "name" => "رشتخوار", "province_id" => 11],
    ["id" => 150, "name" => "زاوه", "province_id" => 11],
    ["id" => 151, "name" => "سبزوار", "province_id" => 11],
    ["id" => 152, "name" => "سرخس", "province_id" => 11],
    ["id" => 153, "name" => "فریمان", "province_id" => 11],
    ["id" => 154, "name" => "فیروزه", "province_id" => 11],
    ["id" => 155, "name" => "قوچان", "province_id" => 11],
    ["id" => 156, "name" => "کاشمر", "province_id" => 11],
    ["id" => 157, "name" => "کلات", "province_id" => 11],
    ["id" => 158, "name" => "گناباد", "province_id" => 11],
    ["id" => 159, "name" => "مشهد", "province_id" => 11],
    ["id" => 160, "name" => "مه ولات", "province_id" => 11],
    ["id" => 161, "name" => "نیشابور", "province_id" => 11],
    ["id" => 162, "name" => "اسفراین", "province_id" => 12],
    ["id" => 163, "name" => "بجنورد", "province_id" => 12],
    ["id" => 164, "name" => "جاجرم", "province_id" => 12],
    ["id" => 165, "name" => "راز و جرگلان", "province_id" => 12],
    ["id" => 166, "name" => "شیروان", "province_id" => 12],
    ["id" => 167, "name" => "فاروج", "province_id" => 12],
    ["id" => 168, "name" => "گرمه", "province_id" => 12],
    ["id" => 169, "name" => "مانه وسملقان", "province_id" => 12],
    ["id" => 170, "name" => "آبادان", "province_id" => 13],
    ["id" => 171, "name" => "آغاجاری", "province_id" => 13],
    ["id" => 172, "name" => "امیدیه", "province_id" => 13],
    ["id" => 173, "name" => "اندیکا", "province_id" => 13],
    ["id" => 174, "name" => "اندیمشک", "province_id" => 13],
    ["id" => 175, "name" => "اهواز", "province_id" => 13],
    ["id" => 176, "name" => "ایذه", "province_id" => 13],
    ["id" => 177, "name" => "باغ ملک", "province_id" => 13],
    ["id" => 178, "name" => "باوی", "province_id" => 13],
    ["id" => 179, "name" => "بندرماهشهر", "province_id" => 13],
    ["id" => 180, "name" => "بهبهان", "province_id" => 13],
    ["id" => 181, "name" => "حمیدیه", "province_id" => 13],
    ["id" => 182, "name" => "خرمشهر", "province_id" => 13],
    ["id" => 183, "name" => "دزفول", "province_id" => 13],
    ["id" => 184, "name" => "دشت آزادگان", "province_id" => 13],
    ["id" => 185, "name" => "رامشیر", "province_id" => 13],
    ["id" => 186, "name" => "رامهرمز", "province_id" => 13],
    ["id" => 187, "name" => "شادگان", "province_id" => 13],
    ["id" => 188, "name" => "شوش", "province_id" => 13],
    ["id" => 189, "name" => "شوشتر", "province_id" => 13],
    ["id" => 190, "name" => "کارون", "province_id" => 13],
    ["id" => 191, "name" => "گتوند", "province_id" => 13],
    ["id" => 192, "name" => "لالی", "province_id" => 13],
    ["id" => 193, "name" => "مسجدسلیمان", "province_id" => 13],
    ["id" => 194, "name" => "هفتگل", "province_id" => 13],
    ["id" => 195, "name" => "هندیجان", "province_id" => 13],
    ["id" => 196, "name" => "هویزه", "province_id" => 13],
    ["id" => 197, "name" => "ابهر", "province_id" => 14],
    ["id" => 198, "name" => "ایجرود", "province_id" => 14],
    ["id" => 199, "name" => "خدابنده", "province_id" => 14],
    ["id" => 200, "name" => "خرمدره", "province_id" => 14],
    ["id" => 201, "name" => "زنجان", "province_id" => 14],
    ["id" => 202, "name" => "سلطانیه", "province_id" => 14],
    ["id" => 203, "name" => "طارم", "province_id" => 14],
    ["id" => 204, "name" => "ماهنشان", "province_id" => 14],
    ["id" => 205, "name" => "آرادان", "province_id" => 15],
    ["id" => 206, "name" => "دامغان", "province_id" => 15],
    ["id" => 207, "name" => "سرخه", "province_id" => 15],
    ["id" => 208, "name" => "سمنان", "province_id" => 15],
    ["id" => 209, "name" => "شاهرود", "province_id" => 15],
    ["id" => 210, "name" => "گرمسار", "province_id" => 15],
    ["id" => 211, "name" => "مهدی شهر", "province_id" => 15],
    ["id" => 212, "name" => "میامی", "province_id" => 15],
    ["id" => 213, "name" => "ایرانشهر", "province_id" => 16],
    ["id" => 214, "name" => "چابهار", "province_id" => 16],
    ["id" => 215, "name" => "خاش", "province_id" => 16],
    ["id" => 216, "name" => "دلگان", "province_id" => 16],
    ["id" => 217, "name" => "زابل", "province_id" => 16],
    ["id" => 218, "name" => "زاهدان", "province_id" => 16],
    ["id" => 219, "name" => "زهک", "province_id" => 16],
    ["id" => 220, "name" => "سراوان", "province_id" => 16],
    ["id" => 221, "name" => "سرباز", "province_id" => 16],
    ["id" => 222, "name" => "سیب و سوران", "province_id" => 16],
    ["id" => 223, "name" => "فنوج", "province_id" => 16],
    ["id" => 224, "name" => "قصرقند", "province_id" => 16],
    ["id" => 225, "name" => "کنارک", "province_id" => 16],
    ["id" => 226, "name" => "مهرستان", "province_id" => 16],
    ["id" => 227, "name" => "میرجاوه", "province_id" => 16],
    ["id" => 228, "name" => "نیک شهر", "province_id" => 16],
    ["id" => 229, "name" => "نیمروز", "province_id" => 16],
    ["id" => 230, "name" => "هامون", "province_id" => 16],
    ["id" => 231, "name" => "هیرمند", "province_id" => 16],
    ["id" => 232, "name" => "آباده", "province_id" => 17],
    ["id" => 233, "name" => "ارسنجان", "province_id" => 17],
    ["id" => 234, "name" => "استهبان", "province_id" => 17],
    ["id" => 235, "name" => "اقلید", "province_id" => 17],
    ["id" => 236, "name" => "بوانات", "province_id" => 17],
    ["id" => 237, "name" => "پاسارگاد", "province_id" => 17],
    ["id" => 238, "name" => "جهرم", "province_id" => 17],
    ["id" => 239, "name" => "خرامه", "province_id" => 17],
    ["id" => 240, "name" => "خرم بید", "province_id" => 17],
    ["id" => 241, "name" => "خنج", "province_id" => 17],
    ["id" => 242, "name" => "داراب", "province_id" => 17],
    ["id" => 243, "name" => "رستم", "province_id" => 17],
    ["id" => 244, "name" => "زرین دشت", "province_id" => 17],
    ["id" => 245, "name" => "سپیدان", "province_id" => 17],
    ["id" => 246, "name" => "سروستان", "province_id" => 17],
    ["id" => 247, "name" => "شیراز", "province_id" => 17],
    ["id" => 248, "name" => "فراشبند", "province_id" => 17],
    ["id" => 249, "name" => "فسا", "province_id" => 17],
    ["id" => 250, "name" => "فیروزآباد", "province_id" => 17],
    ["id" => 251, "name" => "قیروکارزین", "province_id" => 17],
    ["id" => 252, "name" => "کازرون", "province_id" => 17],
    ["id" => 253, "name" => "کوار", "province_id" => 17],
    ["id" => 254, "name" => "گراش", "province_id" => 17],
    ["id" => 255, "name" => "لارستان", "province_id" => 17],
    ["id" => 256, "name" => "لامرد", "province_id" => 17],
    ["id" => 257, "name" => "مرودشت", "province_id" => 17],
    ["id" => 258, "name" => "ممسنی", "province_id" => 17],
    ["id" => 259, "name" => "مهر", "province_id" => 17],
    ["id" => 260, "name" => "نی ریز", "province_id" => 17],
    ["id" => 261, "name" => "آبیک", "province_id" => 18],
    ["id" => 262, "name" => "آوج", "province_id" => 18],
    ["id" => 263, "name" => "البرز", "province_id" => 18],
    ["id" => 264, "name" => "بویین زهرا", "province_id" => 18],
    ["id" => 265, "name" => "تاکستان", "province_id" => 18],
    ["id" => 266, "name" => "قزوین", "province_id" => 18],
    ["id" => 267, "name" => "قم", "province_id" => 19],
    ["id" => 268, "name" => "بانه", "province_id" => 20],
    ["id" => 269, "name" => "بیجار", "province_id" => 20],
    ["id" => 270, "name" => "دهگلان", "province_id" => 20],
    ["id" => 271, "name" => "دیواندره", "province_id" => 20],
    ["id" => 272, "name" => "سروآباد", "province_id" => 20],
    ["id" => 273, "name" => "سقز", "province_id" => 20],
    ["id" => 274, "name" => "سنندج", "province_id" => 20],
    ["id" => 275, "name" => "قروه", "province_id" => 20],
    ["id" => 276, "name" => "کامیاران", "province_id" => 20],
    ["id" => 277, "name" => "مریوان", "province_id" => 20],
    ["id" => 278, "name" => "ارزوییه", "province_id" => 21],
    ["id" => 279, "name" => "انار", "province_id" => 21],
    ["id" => 280, "name" => "بافت", "province_id" => 21],
    ["id" => 281, "name" => "بردسیر", "province_id" => 21],
    ["id" => 282, "name" => "بم", "province_id" => 21],
    ["id" => 283, "name" => "جیرفت", "province_id" => 21],
    ["id" => 284, "name" => "رابر", "province_id" => 21],
    ["id" => 285, "name" => "راور", "province_id" => 21],
    ["id" => 286, "name" => "رفسنجان", "province_id" => 21],
    ["id" => 287, "name" => "رودبارجنوب", "province_id" => 21],
    ["id" => 288, "name" => "ریگان", "province_id" => 21],
    ["id" => 289, "name" => "زرند", "province_id" => 21],
    ["id" => 290, "name" => "سیرجان", "province_id" => 21],
    ["id" => 291, "name" => "شهربابک", "province_id" => 21],
    ["id" => 292, "name" => "عنبرآباد", "province_id" => 21],
    ["id" => 293, "name" => "فاریاب", "province_id" => 21],
    ["id" => 294, "name" => "فهرج", "province_id" => 21],
    ["id" => 295, "name" => "قلعه گنج", "province_id" => 21],
    ["id" => 296, "name" => "کرمان", "province_id" => 21],
    ["id" => 297, "name" => "کوهبنان", "province_id" => 21],
    ["id" => 298, "name" => "کهنوج", "province_id" => 21],
    ["id" => 299, "name" => "منوجان", "province_id" => 21],
    ["id" => 300, "name" => "نرماشیر", "province_id" => 21],
    ["id" => 301, "name" => "اسلام آبادغرب", "province_id" => 22],
    ["id" => 302, "name" => "پاوه", "province_id" => 22],
    ["id" => 303, "name" => "ثلاث باباجانی", "province_id" => 22],
    ["id" => 304, "name" => "جوانرود", "province_id" => 22],
    ["id" => 305, "name" => "دالاهو", "province_id" => 22],
    ["id" => 306, "name" => "روانسر", "province_id" => 22],
    ["id" => 307, "name" => "سرپل ذهاب", "province_id" => 22],
    ["id" => 308, "name" => "سنقر", "province_id" => 22],
    ["id" => 309, "name" => "صحنه", "province_id" => 22],
    ["id" => 310, "name" => "قصرشیرین", "province_id" => 22],
    ["id" => 311, "name" => "کرمانشاه", "province_id" => 22],
    ["id" => 312, "name" => "کنگاور", "province_id" => 22],
    ["id" => 313, "name" => "گیلانغرب", "province_id" => 22],
    ["id" => 314, "name" => "هرسین", "province_id" => 22],
    ["id" => 315, "name" => "باشت", "province_id" => 23],
    ["id" => 316, "name" => "بویراحمد", "province_id" => 23],
    ["id" => 317, "name" => "بهمیی", "province_id" => 23],
    ["id" => 318, "name" => "چرام", "province_id" => 23],
    ["id" => 319, "name" => "دنا", "province_id" => 23],
    ["id" => 320, "name" => "کهگیلویه", "province_id" => 23],
    ["id" => 321, "name" => "گچساران", "province_id" => 23],
    ["id" => 322, "name" => "لنده", "province_id" => 23],
    ["id" => 323, "name" => "آزادشهر", "province_id" => 24],
    ["id" => 324, "name" => "آق قلا", "province_id" => 24],
    ["id" => 325, "name" => "بندرگز", "province_id" => 24],
    ["id" => 326, "name" => "ترکمن", "province_id" => 24],
    ["id" => 327, "name" => "رامیان", "province_id" => 24],
    ["id" => 328, "name" => "علی آباد", "province_id" => 24],
    ["id" => 329, "name" => "کردکوی", "province_id" => 24],
    ["id" => 330, "name" => "کلاله", "province_id" => 24],
    ["id" => 331, "name" => "گالیکش", "province_id" => 24],
    ["id" => 332, "name" => "گرگان", "province_id" => 24],
    ["id" => 333, "name" => "گمیشان", "province_id" => 24],
    ["id" => 334, "name" => "گنبدکاووس", "province_id" => 24],
    ["id" => 335, "name" => "مراوه تپه", "province_id" => 24],
    ["id" => 336, "name" => "مینودشت", "province_id" => 24],
    ["id" => 337, "name" => "آستارا", "province_id" => 25],
    ["id" => 338, "name" => "آستانه اشرفیه", "province_id" => 25],
    ["id" => 339, "name" => "املش", "province_id" => 25],
    ["id" => 340, "name" => "بندرانزلی", "province_id" => 25],
    ["id" => 341, "name" => "رشت", "province_id" => 25],
    ["id" => 342, "name" => "رضوانشهر", "province_id" => 25],
    ["id" => 343, "name" => "رودبار", "province_id" => 25],
    ["id" => 344, "name" => "رودسر", "province_id" => 25],
    ["id" => 345, "name" => "سیاهکل", "province_id" => 25],
    ["id" => 346, "name" => "شفت", "province_id" => 25],
    ["id" => 347, "name" => "صومعه سرا", "province_id" => 25],
    ["id" => 348, "name" => "طوالش", "province_id" => 25],
    ["id" => 349, "name" => "فومن", "province_id" => 25],
    ["id" => 350, "name" => "لاهیجان", "province_id" => 25],
    ["id" => 351, "name" => "لنگرود", "province_id" => 25],
    ["id" => 352, "name" => "ماسال", "province_id" => 25],
    ["id" => 353, "name" => "ازنا", "province_id" => 26],
    ["id" => 354, "name" => "الیگودرز", "province_id" => 26],
    ["id" => 355, "name" => "بروجرد", "province_id" => 26],
    ["id" => 356, "name" => "پلدختر", "province_id" => 26],
    ["id" => 357, "name" => "خرم آباد", "province_id" => 26],
    ["id" => 358, "name" => "دلفان", "province_id" => 26],
    ["id" => 359, "name" => "دورود", "province_id" => 26],
    ["id" => 360, "name" => "دوره", "province_id" => 26],
    ["id" => 361, "name" => "رومشکان", "province_id" => 26],
    ["id" => 362, "name" => "سلسله", "province_id" => 26],
    ["id" => 363, "name" => "کوهدشت", "province_id" => 26],
    ["id" => 364, "name" => "آمل", "province_id" => 27],
    ["id" => 365, "name" => "بابل", "province_id" => 27],
    ["id" => 366, "name" => "بابلسر", "province_id" => 27],
    ["id" => 367, "name" => "بهشهر", "province_id" => 27],
    ["id" => 368, "name" => "تنکابن", "province_id" => 27],
    ["id" => 369, "name" => "جویبار", "province_id" => 27],
    ["id" => 370, "name" => "چالوس", "province_id" => 27],
    ["id" => 371, "name" => "رامسر", "province_id" => 27],
    ["id" => 372, "name" => "ساری", "province_id" => 27],
    ["id" => 373, "name" => "سوادکوه", "province_id" => 27],
    ["id" => 374, "name" => "سوادکوه شمالی", "province_id" => 27],
    ["id" => 375, "name" => "سیمرغ", "province_id" => 27],
    ["id" => 376, "name" => "عباس آباد", "province_id" => 27],
    ["id" => 377, "name" => "فریدونکنار", "province_id" => 27],
    ["id" => 378, "name" => "قایم شهر", "province_id" => 27],
    ["id" => 379, "name" => "کلاردشت", "province_id" => 27],
    ["id" => 380, "name" => "گلوگاه", "province_id" => 27],
    ["id" => 381, "name" => "محمودآباد", "province_id" => 27],
    ["id" => 382, "name" => "میاندورود", "province_id" => 27],
    ["id" => 383, "name" => "نکا", "province_id" => 27],
    ["id" => 384, "name" => "نور", "province_id" => 27],
    ["id" => 385, "name" => "نوشهر", "province_id" => 27],
    ["id" => 386, "name" => "آشتیان", "province_id" => 28],
    ["id" => 387, "name" => "اراک", "province_id" => 28],
    ["id" => 388, "name" => "تفرش", "province_id" => 28],
    ["id" => 389, "name" => "خمین", "province_id" => 28],
    ["id" => 390, "name" => "خنداب", "province_id" => 28],
    ["id" => 391, "name" => "دلیجان", "province_id" => 28],
    ["id" => 392, "name" => "زرندیه", "province_id" => 28],
    ["id" => 393, "name" => "ساوه", "province_id" => 28],
    ["id" => 394, "name" => "شازند", "province_id" => 28],
    ["id" => 395, "name" => "فراهان", "province_id" => 28],
    ["id" => 396, "name" => "کمیجان", "province_id" => 28],
    ["id" => 397, "name" => "محلات", "province_id" => 28],
    ["id" => 398, "name" => "ابوموسی", "province_id" => 29],
    ["id" => 399, "name" => "بستک", "province_id" => 29],
    ["id" => 400, "name" => "بشاگرد", "province_id" => 29],
    ["id" => 401, "name" => "بندرعباس", "province_id" => 29],
    ["id" => 402, "name" => "بندرلنگه", "province_id" => 29],
    ["id" => 403, "name" => "پارسیان", "province_id" => 29],
    ["id" => 404, "name" => "جاسک", "province_id" => 29],
    ["id" => 405, "name" => "حاجی اباد", "province_id" => 29],
    ["id" => 406, "name" => "خمیر", "province_id" => 29],
    ["id" => 407, "name" => "رودان", "province_id" => 29],
    ["id" => 408, "name" => "سیریک", "province_id" => 29],
    ["id" => 409, "name" => "قشم", "province_id" => 29],
    ["id" => 410, "name" => "میناب", "province_id" => 29],
    ["id" => 411, "name" => "اسدآباد", "province_id" => 30],
    ["id" => 412, "name" => "بهار", "province_id" => 30],
    ["id" => 413, "name" => "تویسرکان", "province_id" => 30],
    ["id" => 414, "name" => "رزن", "province_id" => 30],
    ["id" => 415, "name" => "فامنین", "province_id" => 30],
    ["id" => 416, "name" => "کبودرآهنگ", "province_id" => 30],
    ["id" => 417, "name" => "ملایر", "province_id" => 30],
    ["id" => 418, "name" => "نهاوند", "province_id" => 30],
    ["id" => 419, "name" => "همدان", "province_id" => 30],
    ["id" => 420, "name" => "ابرکوه", "province_id" => 31],
    ["id" => 421, "name" => "اردکان", "province_id" => 31],
    ["id" => 422, "name" => "اشکذر", "province_id" => 31],
    ["id" => 423, "name" => "بافق", "province_id" => 31],
    ["id" => 424, "name" => "بهاباد", "province_id" => 31],
    ["id" => 425, "name" => "تفت", "province_id" => 31],
    ["id" => 426, "name" => "خاتم", "province_id" => 31],
    ["id" => 427, "name" => "مهریز", "province_id" => 31],
    ["id" => 428, "name" => "میبد", "province_id" => 31],
    ["id" => 429, "name" => "یزد", "province_id" => 31],
];
